### ISSUE TITLE
Too many file descriptors opened on server side 

### ISSUE THREAD

**Issue by TheSithPadawan** [TheSithPadawan/CSE222A-CourseProject#1]
Load balancer fails when there are too many requests come in.
Each request takes up a socket, so this would cause an OS error.
This shows up on vegeta end as:
```
Get http://localhost:8080/foo?type=b: read tcp 127.0.0.1:51356->127.0.0.1:8080: read: connection reset by peer
```

**Comment by moment8890** [comment]
This should be handled via catching Exceptions in RequestHandler by now.
